apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl  
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: remove-default-gp2-sc-to-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: internal-kubectl    
---
apiVersion: batch/v1
kind: Job
metadata:
  name: remove-default-gp2-sc
  namespace: kube-system
spec:
  template:
    metadata:
      name: remove-default-gp2-sc
    spec:
      serviceAccountName: internal-kubectl
      containers:
      - name: kubectl-remove-sc
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
         - "kubectl delete sc gp2"
      restartPolicy: Never 