apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl  
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-sc
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources:
      - storageclass
    verbs:
      - get
      - list
      - delete      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-default-sc-to-sa
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
roleRef:
  kind: Role
  name: modify-sc
  apiGroup: rbac.authorization.k8s.io      
---
apiVersion: batch/v1
kind: Job
metadata:
  name: remove-default-gp2-sc
  namespace: kube-system
spec:
  template:
    metadata:
      name: remove-default-gp2-sc
    spec:
      serviceAccountName: internal-kubectl
      containers:
      - name: kubectl-remove-sc
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
         - "kubectl delete sc gp2"
      restartPolicy: Never 