apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# https://github.com/kubeflow/manifests#kserve
# The actual kustomization.yaml files from kubeflow v1.7.0 kserve: 
# github.com/kubeflow/manifests/blob/v1.7.0/contrib/kserve/kserve/kustomization.yaml
- github.com/kubeflow/manifests/contrib/kserve/kserve?ref=v1.7.0
# github.com/kubeflow/manifests/blob/v1.7.0/contrib/kserve/models-web-app/overlays/kubeflow/kustomization.yaml
- github.com/kubeflow/manifests/contrib/kserve/models-web-app/overlays/kubeflow?ref=v1.7.0

patchesStrategicMerge:
- patches/inferenceservice-config.yaml