# https://eksctl.io/usage/schema/
#

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  # Name of your cluster, change to whatever you find fit.
  # If changed, make sure to change all nodegroup tags from 
  # 'k8s.io/cluster-autoscaler/cluster-name: "owned"' --> 'k8s.io/cluster-autoscaler/your-new-name: "owned"'
  name: araneae
  # choose your region wisely, this will significantly impact the cost incurred
  region: us-west-2 # Oregon
  # Kubernetes version 
  version: '1.20' 
  tags:
    # Add more cloud tags if needed for billing
    environment: development
    creator: paloul
    project: araneae
    cluster: araneae

iam:
  # https://eksctl.io/usage/schema/#iam-withOIDC
  withOIDC: true

vpc:
  cidr: 10.10.0.0/16
  # https://eksctl.io/usage/vpc-networking/#nat-gateway
  nat:
    gateway: Single # other options: Disable, Single (default), HighlyAvailable 

  # https://eksctl.io/usage/vpc-networking/#managing-access-to-the-kubernetes-api-server-endpoints
  clusterEndpoints:
    publicAccess:  true   # Should eventually be false, just for security sake
    privateAccess: true

# Add all possible AZs to ensure nodes can be spun up in any AZ later on. 
# THIS CAN'T BE CHANGED LATER. YOU WILL HAVE TO CREATE A NEW CLUSTER TO ADD NEW AZ SUPPORT.
# This list applies to the whole cluster and isn't specific to nodegroups
availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]

nodeGroups:
  - name: ng-util
    desiredCapacity: 1
    minSize: 1
    maxSize: 9
    volumeSize: 30
    volumeType: gp3
    instanceType: t3a.medium 
    availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]
    asgMetricsCollection:
      # https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-instance-monitoring.html
      - granularity: 1Minute
        metrics:
          - GroupMinSize
          - GroupMaxSize
          - GroupDesiredCapacity
          - GroupInServiceInstances
          - GroupPendingInstances
          - GroupStandbyInstances
          - GroupTerminatingInstances
          - GroupTotalInstances
    labels:
      node-class: "utility"
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/node-template/label/node-class: utility
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/araneae: "owned"
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true

  - name: ng-frontend
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 30
    volumeType: gp3
    instanceType: t3a.small
    availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]
    asgMetricsCollection:
      # https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-instance-monitoring.html
      - granularity: 1Minute
        metrics:
          - GroupMinSize
          - GroupMaxSize
          - GroupDesiredCapacity
          - GroupInServiceInstances
          - GroupPendingInstances
          - GroupStandbyInstances
          - GroupTerminatingInstances
          - GroupTotalInstances
    labels:
      node-class: "front-end"
    taints:
      only-frontend: "true:NoSchedule"
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/node-template/label/node-class: front-end
      k8s.io/cluster-autoscaler/node-template/taint/only-frontend: "true:NoSchedule"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/araneae: "owned"
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true

  - name: ng-reasoner
    desiredCapacity: 3
    minSize: 3
    maxSize: 6
    volumeSize: 30
    volumeType: gp3
    instanceType: t3a.medium
    availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]
    asgMetricsCollection:
      # https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-instance-monitoring.html
      - granularity: 1Minute
        metrics:
          - GroupMinSize
          - GroupMaxSize
          - GroupDesiredCapacity
          - GroupInServiceInstances
          - GroupPendingInstances
          - GroupStandbyInstances
          - GroupTerminatingInstances
          - GroupTotalInstances
    labels:
      node-class: "reasoner"
    taints:
      only-reasoner: "true:NoSchedule"
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/node-template/label/node-class: reasoner
      k8s.io/cluster-autoscaler/node-template/taint/only-reasoner: "true:NoSchedule"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/araneae: "owned"
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true

  - name: ng-cache
    desiredCapacity: 6
    minSize: 6
    maxSize: 6
    volumeSize: 30
    volumeType: gp3
    instanceType: t3a.medium
    availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]
    asgMetricsCollection:
      # https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-instance-monitoring.html
      - granularity: 1Minute
        metrics:
          - GroupMinSize
          - GroupMaxSize
          - GroupDesiredCapacity
          - GroupInServiceInstances
          - GroupPendingInstances
          - GroupStandbyInstances
          - GroupTerminatingInstances
          - GroupTotalInstances
    labels:
      node-class: "cache"
    taints:
      only-cache: "true:NoSchedule"
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/node-template/label/node-class: cache
      k8s.io/cluster-autoscaler/node-template/taint/only-cache: "true:NoSchedule"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/araneae: "owned"
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true

  - name: ng-data
    desiredCapacity: 1
    minSize: 1
    maxSize: 12
    volumeSize: 30
    volumeType: gp3
    instanceType: m5ad.large # EBS + 1 x 75Gib NVMe SSD, 2 core, 8 gb mem
    availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]
    asgMetricsCollection:
      # https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-instance-monitoring.html
      - granularity: 1Minute
        metrics:
          - GroupMinSize
          - GroupMaxSize
          - GroupDesiredCapacity
          - GroupInServiceInstances
          - GroupPendingInstances
          - GroupStandbyInstances
          - GroupTerminatingInstances
          - GroupTotalInstances
    labels:
      node-class: "data"
    taints:
      only-data: "true:NoSchedule"
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/node-template/label/node-class: data
      k8s.io/cluster-autoscaler/node-template/taint/only-data: "true:NoSchedule"
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/araneae: "owned"
    iam:
      withAddonPolicies:
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
    # Prebootstrap Commands set up the file system on the instance drive, 
    #  but Rook-Ceph needs to know only the device path, it formats itself
    # preBootstrapCommands: 
    #   - "mkfs -t ext4 /dev/nvme1n1"
    #   - "mkdir -p /ephemeral"
    #   - "mount /dev/nvme1n1 /ephemeral"
    #   - "chown ec2-user:ec2-user /ephemeral"
