# Basic Pod that hosts a single Redis Master instance
# For authentication session store this is plenty 
# In the future this might want to be a cluster spread
# across the three availability zones in vpc. Though
# if this goes down, since it only handles the auth
# session cookie, it is not detrimental to user experience.
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: auth
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.5"
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis-config
        items:
        - key: redis-config
          path: redis.conf