apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - namespace.yaml

# Hashicorp Vault helm chart
# https://learn.hashicorp.com/tutorials/vault/kubernetes-raft-deployment-guide?in=vault/kubernetes
helmChartInflationGenerator:
- chartName: hashicorp/vault
  chartRepoUrl: https://helm.releases.hashicorp.com
  chartVersion: 0.6.0
  releaseName: vault
  releaseNamespace: vault
  # override with these custom values
  values: values.yaml

generatorOptions:
  disableNameSuffixHash: true