apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  ## Common
  - argocd-applications/istio-operator.yaml
  - argocd-applications/istio.yaml    
  - argocd-applications/istio-resources.yaml
  - argocd-applications/cert-manager-dns-01.yaml
  - argocd-applications/rook-ceph.yaml
  - argocd-applications/redis-cluster.yaml

  # Auth 
  - argocd-applications/oidc-auth-external.yaml
  # - argocd-applications/oidc-auth-keycloak.yaml

  ## System
  - argocd-applications/cluster-autoscaler.yaml
  - argocd-applications/aws-load-balancer-controller.yaml
  - argocd-applications/external-dns.yaml
  - argocd-applications/external-secrets.yaml

  ## Monitoring
  - argocd-applications/metrics-server.yaml

  ## Araneae
  - argocd-applications/araneae-dashboard.yaml
  - argocd-applications/araneae-reasoner.yaml
