apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  ## Certificates
  - argocd-applications/cert-manager-dns-01.yaml
  - argocd-applications/cert-manager-certificates.yaml

  ## Istio
  - argocd-applications/istio-operator.yaml
  - argocd-applications/istio.yaml
  - argocd-applications/istio-resources.yaml

  ## Data infrastructure
  - argocd-applications/rook-ceph.yaml

  ## Generic cloud-native infrastructure support
  - argocd-applications/keda.yaml
  - argocd-applications/knative.yaml
  - argocd-applications/external-dns.yaml
  # - argocd-applications/sealed-secrets.yaml # Sealed Secrets is installed before our application. Not controlled by Argo. Read Deploy.md 

  ## AWS specific infrastructure support
  - argocd-applications/cluster-autoscaler.yaml
  - argocd-applications/aws-load-balancer-controller.yaml
  - argocd-applications/aws-eks-resources.yaml

  ## Databases
  # - argocd-applications/postgres.yaml # Postgresql Database with Primary and 2 Read Replicas
  # - argocd-applications/cassandra.yaml # Cassandra from Bitnami. 3 Seeds Nodes with 1 Replication
  #### Choose one Mongodb deployment type: Single or Sharded
  # - argocd-applications/mongodb-single.yaml # MongoDB single standalone server
  # - argocd-applications/mongodb-sharded.yaml # MongoDB Sharded cluster with 1 configsrv, 3 mongos router, 3 data shards

  ## Cache
  #### Choose one Redis deployment type: Cluster or Server
  # - argocd-applications/redis-cluster.yaml # Redis Cluster with 6 nodes total, 3 masters and 3 read-only replicas
  # - argocd-applications/redis-server.yaml # Redis Standalone with just one Master and its read-only Slave

  ## Messaging
  # - argocd-applications/kafka.yaml
  # - argocd-applications/rabbitmq.yaml

  # Pick *one* of the following applications:
  # - argocd-applications/oidc-auth-on-cluster-dex.yaml
  - argocd-applications/oidc-auth-on-cluster-keycloak.yaml
  # - argocd-applications/oidc-auth-external.yaml

  ## Monitoring
  - argocd-applications/metrics-server.yaml # FYI: Needed for knative
  #- argocd-applications/redis-insight.yaml
  #- argocd-applications/monitoring-resources.yaml
  #- argocd-applications/kube-prometheus-stack.yaml
  #- argocd-applications/loki-stack.yaml
  #- argocd-applications/kiali.yaml
  #- argocd-applications/jaeger.yaml

  ## Kubeflow
  - argocd-applications/central-dashboard-mlflow.yaml
  # Pick the ones you want here:
  - argocd-applications/profile-controller_access-management.yaml
  - argocd-applications/kubeflow-namespace.yaml
  - argocd-applications/kubeflow-roles.yaml
  - argocd-applications/pipelines.yaml
  - argocd-applications/katib.yaml
  - argocd-applications/kfserving.yaml
  - argocd-applications/pod-defaults.yaml
  - argocd-applications/jupyter-web-app.yaml
  - argocd-applications/notebook-controller.yaml
  # - argocd-applications/tensorboard-controller.yaml
  # - argocd-applications/tensorboards-web-app.yaml
  # - argocd-applications/volumes-web-app.yaml

  ## Araneae
  # - argocd-applications/araneae-dashboard.yaml
  # - argocd-applications/araneae-reasoner.yaml
