apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  ## Common
  - argocd-applications/istio-operator.yaml
  - argocd-applications/istio.yaml    
  - argocd-applications/istio-resources.yaml
  - argocd-applications/cert-manager-dns-01.yaml
  - argocd-applications/rook-ceph.yaml 

  ## Databases
  - argocd-applications/postgres.yaml # Postgresql Database with Primary and 2 Read Replicas
  - argocd-applications/mongodb-sharded.yaml # MongoDB Sharded cluster with 1 configsrv, 3 mongos router, 3 data shards
  - argocd-applications/cassandra.yaml # Cassandra from Bitnami. 3 Seeds Nodes with 1 Replication
  #### Choose one Redis deployment type: Cluster or Server
  - argocd-applications/redis-cluster.yaml # Redis Cluster with 6 nodes total, 3 masters and 3 read-only replicas
  # - argocd-applications/redis-server.yaml # Redis Standalone with just one Master and its read-only Slave

  # Messaging
  - argocd-applications/kafka.yaml
  - argocd-applications/rabbitmq.yaml

  # Auth 
  - argocd-applications/oidc-auth-external.yaml
  # - argocd-applications/oidc-auth-keycloak.yaml

  ## System
  - argocd-applications/cluster-autoscaler.yaml
  - argocd-applications/aws-load-balancer-controller.yaml
  - argocd-applications/external-dns.yaml
  - argocd-applications/external-secrets.yaml
  - argocd-applications/keda.yaml

  ## Monitoring
  - argocd-applications/metrics-server.yaml 
  - argocd-applications/redis-insight.yaml

  ## Araneae
  - argocd-applications/araneae-dashboard.yaml
  - argocd-applications/araneae-reasoner.yaml
