apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serving-core-v1.8.0.yaml
- net-istio-v1.8.0.yaml
- allow-all-ns-knative-authorization-policy.yaml
- peerauthentication-force-strict-mtls.yaml
# - monitoring/

# patches

# removals
patches:
- path: patches/config-istio.yaml
- path: patches/config-logging.yaml
- path: patches/config-network.yaml
- path: patches/config-observability.yaml
- path: patches/config-domain.yaml
- path: patches/config-deployment.yaml
- path: patches/enable-istio-injection.yaml
- path: patches/enable-sidecar-istio-controller.yaml
#- path: removals/remove-knative-ingress-gateway.yaml
- path: removals/remove-knative-local-gateway.yaml
- path: removals/remove-knative-local-gateway-service.yaml
