apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph

resources:
- crds.yaml
- common.yaml
- operator.yaml
- cluster.yaml
- storageclass-block.yaml
- storageclass-object.yaml
