#################################################################################################################
# This is a sample pod definition that shows how to inject a rook-ceph bucket information.
#
#  https://github.com/rook/rook/blob/master/Documentation/ceph-object-bucket-claim.md#app-pod
# 
#   "configMapRef": makes available to the pod as env variables: BUCKET_HOST, BUCKET_PORT, BUCKET_NAME
#   "secretRef": makes available to the pod as env variables: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
#################################################################################################################

apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  namespace: dev-user
spec:
  containers:
  - name: mycontainer
    image: redis
    envFrom:
    - configMapRef:
        name: araneae-general-bucket-claim # This should match name of the Object Bucket Claim
    - secretRef:
        name: araneae-general-bucket-claim # This should match name of the Object Bucket Claim