apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../base
# Uses External-Secrets with AWS Secret Manager. Trying to do secrets with sealed-secrets instead.
# Look at the setup_credentials_argocd.sh script to look how Private repo git credentials are created
# as secrets for consumption by argocd to access the private repo.
- secret.yaml 

patchesStrategicMerge:
- patches/configmap-patch.yaml