kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: git-repo-secret
  namespace: argocd
  creationTimestamp: null
spec:
  template:
    metadata:
      name: git-repo-secret
      namespace: argocd
      creationTimestamp: null
  encryptedData:
    HTTPS_PASSWORD: AgCYx6Gy9s4dY7joaDNTsibbkHd4du8ueMoZ8sZ3aZoycIwkFRuxI7LwA0OowxVgSbB+jmpRx3Y84GlCLqL1VU5v5otEEwJr/Da5u3noxZupX83UtbNNozhYu7Ia9FiEvtLAkofH577mw0BKmh+FmQb7eMcOtMIr3rcVQ7jYO1h0MZoUrkqojy+N5lQ1fwNXcjddif1NorcSTMcM5a/6WcL4vTTCjyhBk/b8afOtQxuf1kHYi/m7ChKDiqVLWbPOmLRwYyb0Ntlw5oLXuzxP2fiSOIVW/Px3DeuENcmXgCJmLrkNO2jwyhUg8orlOXRyaYeBfq8mZS1SomIhhJeCuIbfYy8qppRd3OX6nJAk/8cYOHmQbZno+TFZWooDx9/lmZ5QBncRIhtuhTXoXNt9frBRE9xDUeIqYSg3hVVwmL/f5TxInPPBwe1KV2S1R2nAa0/YO6FDxJQgya6EfwF/9kcOMJm9u6z5kbTq3c3ikBx61tPvEFkngFrvQIRs/oRVQR6idMnISh9EDm406aIv6F070QX7VVHypCrL0H6q7OpTaiV2Eyf5azKZh0h9KP9A+d4mi+tRaajlZUvLbZnKIpk2OBptJ9hilKxyLhFxenJCYwZY9hoZCWiUu9d0ykvXrGdXMMUmE6T80KqtGmKgK7u7ct2HtyTOx3hOOgNVSPDla73UqIVDVr/Ulo1vNwKZ/fAyc83aGTJ+91wRpdhlRE0lPrQB/uh1Z/+QF3FB4XEQMEgutCQg0Kw5
    HTTPS_USERNAME: AgBnk2ReQHlyenMTVQdAtePpYI+URsqXXNalXB2A0WrS39Qe+y/IEza/xwKryWpcL4hjLnC2GgbDEMkyux3ZCaqU73zklOkTYU+96lL15iLL9UET+jirK1u5p1IEIyjZTV/sg5I2/g5BY+Gx2agcC/0LGMU74gnjk7wnDgpPYqha4vBGpgXvc3nzYUUf5axjG9R5MKktRmLDUF77/m5fGt3qTa1hb6x3GZ9/HicF0nDp1CpFCchOTEJeDDxD0gsHi1701xALD7ziBGZZgUceboeVTFo25rKD4vKd03xKvh2q/+nv/l2N4ws/DH2wQ57r7Wy+xf7zVqN9t9E6+VkSsXBnFxfQ01oBzSky4t/uAc51onmKtvdxOuxHfZ5zo/SNkpZAYc9PWhHSHfTu96gwWYQy6YDjbyt12F7fHcpT+fmaxbpjX/5zmbOWicZOCC4bdG/ofsR29xz50ttsTPB9C/IUA/vnatv5x8hmNjIvd1xla9O7ff3mLr1LXSNDjXc6HmkRZBwOvfzug5K2pv+JWp9X6FGauy7HJAWzJSWl14fVok/nKb60jVVU10c93fF4eaPjA5C16U5Aj1VMP+VIB4mbP0wjNt3g6cDxJ06Jg0LmQeObDuEJ+QwWGJRRmXOhGiJWoIs8A0SKwWjnmBW7sSCHub+sih0oaOmVfOCzlfB7a2kLb3atbjviWXSZaBU4h6R88VuKdO4=
