kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: git-repo-secret
  namespace: argocd
  creationTimestamp: null
spec:
  template:
    metadata:
      name: git-repo-secret
      namespace: argocd
      creationTimestamp: null
  encryptedData:
    HTTPS_PASSWORD: AgCeLEB7pZ+P/RbJNe9IvnQfEaxs2UPPj35PtUcP+mrW4Jl8UvFhVU420XjQBRb1OYsGruRSqFPnsfajfi5ryI89HpSimTDoEX7cPC1cDhbSmB9wHqJVzjefWBl7KMC5J1vF27BcqmzmVtPcnLIXJ1R+vpcTReyZuSnYeNJlck50b/hyqUTThVWJBuAmHiYpc5JIVwQGP6OEPV7C6MTHdLFggoBpt4DZRlJfyjBC42i3cg0tcn+oCs0MWrF5pIJBkfpSCcE+f/8+nqF3RgtEJAw0z3UXxghlqljtVTy9H6vLXCXSjRz7WfFXpnKXURwWyjcQZThcISxwn8A8gr+vZeF6sO6H4TIdGBXJvbd+dQFcn5jkcDChQQUOq+YFe6VZ35hMDV4yOAyTEPAPanZ7Ht+eGFane64R55sAMdkIa6PklY/QjKd4dI2JRq3QzOzuzfIat/jPZhuxoNd3VGxpZMTlwGHLlvAuCdA5uGpMPgLvpgFhP4ItFbFigeMzdokWO/JFiWdl4Y8eOC0MjG5SZmcBoToXtFPvTmcChTaH6Tg4NNxBosfOy/DecsOE6+TvvuHfj1Ov9fBeX4fIO4y5IlzhgWNOfpBVsoY2jNWawm6sz+UVhmV1g8S+aoyNDiW/Yz2tYqtlCxbpcqorZPAMcNNXnRss0qNmOsQjfP2tTyVjR9TYHDGXZQgkaiWLJGAbNsBEXKjUHzMjuSRbquGrYxKDTAlI2yIjwkIcyK24RvAOClynzSO7jq+x
    HTTPS_USERNAME: AgA0XyvJ3o4aEIaYO50sN8t6zkA/kHFqcmjwwjC3EZeRPP85xww6xAIpoUFxQ7GJ3Ov1Xdxr5VcIxWKwWe9PcY4G9/wwp2RtO4JiYCnpjZBfSvIwTs0MRB3ZQSlHNJcIo5bd+Es5aCSJ003VRbJ6dWoLyBaM+fpM7OIsl2IgZOLgoMhLewvph25MalLL6XMiN603Gn9cVcY0Ky2QhnWBFHyqUUB6WlRvYOyDRye7ySNT3FvpKzamf+wQPqhFz9kdljaSi2WDWOPpPTfEk4CKicmTKg1vC0qcSwWTEuPzAb62UIrvK2WruLkJCTPpXrZr00S+6NA0a4Rdqkflj0djDrq9pITFOfufngoy4cyd8ynmp9JjEDluDlXV2yMKDktbZCZ33Z9a+uuI0RXVYVVaWvN7wC2k6vQhuXHlHZaGRk7BwaZ0uB3MOvj9aEUi4CMLdkoUgcQPuFL1j+Mg4LzF8yS9j2aeB8c7krLxwlSqqUGlJXAMVJEJblJ76BJmmZevd/kJQo3pTsVWrwyVGzeyXPPXNRypyyvguXtuXOLocloIHHNx0M+fswTE5eR3gP/D79MfsRLFQdPCvPMqp8xyxpnXx7sND6KHDTIr9qjPCkmBnyxOyIKFUnnWMlDQQOplL1YklsmVf91XmWuIFctF8XFGJPv+yIXR9prorvrktXklM2DLNy7HAqCa4XKTlvyws2rJxUdj25E=
