kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: git-repo-secret
  namespace: argocd
  creationTimestamp: null
spec:
  template:
    metadata:
      name: git-repo-secret
      namespace: argocd
      creationTimestamp: null
  encryptedData:
    HTTPS_PASSWORD: SOMETHING
    HTTPS_USERNAME: SOMETHINGELSE
