---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-cache-database
  namespace: kubeflow
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - name: create-cache-database
        image: public.ecr.aws/atcommons/utils/mysql-db-creator:latest
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: pipelines-postgresql-config
              key: POSTGRESQL_HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: pipelines-postgresql-config
              key: POSTGRESQL_PORT
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: pipelines-postgresql-secret
              key: POSTGRESQL_USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: pipelines-postgresql-secret
              key: POSTGRESQL_PASSWORD
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: pipelines-postgresql-config
              key: DB_NAME_CACHE
      restartPolicy: Never
  backoffLimit: 5
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-pipelines-database
  namespace: kubeflow
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - name: create-pipelines-database
        image: public.ecr.aws/atcommons/utils/mysql-db-creator:latest
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: pipelines-postgresql-config
              key: POSTGRESQL_HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: pipelines-postgresql-config
              key: POSTGRESQL_PORT
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: pipelines-postgresql-secret
              key: POSTGRESQL_USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: pipelines-postgresql-secret
              key: POSTGRESQL_PASSWORD
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: pipelines-postgresql-config
              key: DB_NAME_PIPELINES
      restartPolicy: Never
  backoffLimit: 5
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-metadata-database
  namespace: kubeflow
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - name: create-metadata-database
        image: public.ecr.aws/atcommons/utils/mysql-db-creator:latest
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: pipelines-postgresql-config
              key: POSTGRESQL_HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: pipelines-postgresql-config
              key: POSTGRESQL_PORT
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: pipelines-postgresql-secret
              key: POSTGRESQL_USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: pipelines-postgresql-secret
              key: POSTGRESQL_PASSWORD
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: pipelines-postgresql-config
              key: DB_NAME_METADATA
      restartPolicy: Never
  backoffLimit: 5