apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# https://github.com/kubeflow/manifests#notebooks
# The actual kustomization.yaml files from kubeflow v1.7.0 Jupyter Web App: 
# github.com/kubeflow/manifests/blob/v1.7.0/apps/jupyter/jupyter-web-app/upstream/overlays/istio/kustomization.yaml
- github.com/kubeflow/manifests/apps/jupyter/jupyter-web-app/upstream/overlays/istio?ref=v1.7.0

patchesStrategicMerge:
- patches/configs/spawner-ui-config.yaml