kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: oauth2-redis
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: oauth2-redis
      namespace: auth
      creationTimestamp: null
  encryptedData:
    redis-password: AgCzxcjNGp4AEPeDqfX3UyDetRyzShjTaQQEI9T9RjtZw5GlCVZpaAfLFGACaKhgq3HUR+seqREIM3jzwIcWBQfYaikM+oLhSHBx7A+KOfp8WNJi81R+bw6uuDjxt2zaNzm/xdXJVmp9uyvPVCpq8taQ+pWc8EgcvpP5Zyz0w+ZbUlfKXisEuQcrB9V7GXu/6rh5WZaIvd7FlQprcuJY0l1L4GCK2EOPiqW/ES4dzTDhxLbvRe2D6+a0BEGCWyscAzMNZnAM+Dgl22zvrCagivNJg2Upvc7ipQ1nFKZ6LrlLQPHUoLunvENktyimYp5eypWYl/Z1/1v+FXly06TN+eX8qZkrWQd9InuP6xQHJGV0yPKKbW4h4ujJV6ycGNl1bymFrbPq0jSEQTpwTMfsBWBVYC4RHzbq7KvyF9iA9mqgiOkUARHQen2vBobls/cqR9AGecA1KDF+O8RWIWe2xedbaldlxIGmll8Et2Mgvs200wluBmiATmbDihYUG/7GwyGVD/tR6vO0JXhj4d9b+k3FtlPGjyzdxbZdtNO3OlSvCTFLMajgRg6uncyv6KBxxNq0LrGTehFTIZ01lzSDiRY9XJy+up4y+KthHXH8ELQr7jfBACTWjqoic1eQzJRXyA3mq/E53j+5HEkdKneZz5vMH00LsPOqBpFtv6We9T6Ba+GkLuX4bX86K7FhdLSZQXweYX/x394JLaqX0FRYRLcxSS5vlJo87e5Lr2BpCGeqOg==
