apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oauth2-proxy-logout
  namespace: auth
spec:
  gateways:
  - kubeflow/kubeflow-gateway # This points to the main gateway created in istio-resources that allows for ingress traffic from outside
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /logout
    rewrite:
      uri: "/oauth2/sign_out"
    route:
    - destination:
        host: oauth2-proxy.auth.svc.cluster.local
        port:
          number: 4180
