kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: oauth2-redis
  namespace: auth
  creationTimestamp:
spec:
  template:
    metadata:
      name: oauth2-redis
      namespace: auth
      creationTimestamp:
    data:
  encryptedData:
    redis-password: SOMETHING