apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:

    # https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller
    # https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller

    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.5.3 # Chart version 1.5.3, Application Version 2.5.2
    chart: aws-load-balancer-controller
    helm:
      parameters:
        - name: serviceAccount.name
          value: aws-load-balancer-controller
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: arn:aws:iam::654383687924:role/eksctl-araneae-addon-iamserviceaccount-kube-Role1-11CQK7WAJ5UGR
        - name: clusterName
          value: araneae
        - name: vpcId
          value: vpc-0f766b79de5e662a4
        - name: region
          value: us-west-2
        - name: serviceAccount.create
          value: "true"
        - name: rbac.create
          value: "true"
        - name: resources.limits.cpu
          value: 100m
        - name: resources.limits.memory
          value: 300Mi
        - name: resources.requests.cpu
          value: 100m
        - name: resources.requests.memory
          value: 300Mi
        - name: nodeSelector.node-class
          value: core
        # https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller#installing-cert-manager
        - name: enableCertManager
          value: "true"
        - name: cluster.dnsDomain
          value: araneae.io
        - name: clusterSecretsPermissions.allowAllSecrets
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
