apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager
  namespace: cert-manager
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::654383687924:role/eksctl-araneae-addon-iamserviceaccount-cert-Role1-CB6YI9R87OPD
