kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: mysql-secret
  namespace: kubeflow
  creationTimestamp: null
spec:
  template:
    metadata:
      name: mysql-secret
      namespace: kubeflow
      creationTimestamp: null
  encryptedData:
    password: AgDcWTkt0Y9ZSaWdecahsJPyr4w99Uc5PVbeG0gbwHtxB7q7la1qqrGN13cCbj0QpQuU8GkrKh2mejViHouYjMrZewobB34ekRtv/hTse14MdTxubBvFhOnyubWbsntZdO8goIwO5ExTt6CEKUvDWcKllR+UTy8oGkNHpNLRcWcM6lqwqNdl4TkKpWQ8bBbQR7RSJGSTqzr5T+Uzo9KK0kpxqXG7gqBPsPTBf3BpfquLH6KefMdR9G9c/cl/lj3sSxYeEhRlW8mAPoAB1mla1Il4vUUM+zLd43EpbjNwmE2yQpl2zsPRjLOkAz5dRRpo6xAtZVu/R7z7JsBF/v6G08ZY7ENqVlXqKss8m+XwZWptnjQPfDUViSM2CtwRjKaJfgIk/k+sAkp1688TrSxhH2It9Ags4Vqi/EQ7cw0elSmyZwBPXyLgZwACcTwIfgnyPHRZb5zuLcnc7Qtr/7/9o6mklGiZixtSUqg7I6csiXcQ4NOB8i21a0mPeLgNyXwD4TiPAMd8pEK/ZX0xx5xNndb+ZuSLPQMBLAUS4lUjJp22gVrDmnVRn8sGOcLsTko6zAs0BC63s76S8cSyvDccEMeVN74Qb5DqTp/aSL6cXKW3Wl/eM+hZJsdvn0Z/tcEWo1ROxpzxQxeEnmYSbpgTSLycYcxTUisRGegq9xiCwiXYnaOQApdRlV2mUjFP+y/DP8U5ickAh4fRHrj8R/0qfC9tjb70YNyBPAnXjDtEtW3XZw==
    username: AgBl5IaLGdFluVgszfttq/EII0weYLeb+sdhCeo9nY4ousn6Tkmjh5YDm0Ix3MD5jTQRRKtQW6R8eczUf7bLwxdCrScOF+BM64CBPwsKRxuQcPlbYdS5TWrJ2pnIe9m+ftC5wwvLS17j4MO6g/JsYJelEnMJuns5b1xNK/jL66UZuCRYASPQzH7DhCsD3ooa+lEarK9qQyfNfkuSz23kZsD9gGRoMjHyAA5j7QX2YltW7f1O7OethJMcUWxKskIsk/nBBNgDnfaj5+FroI+4u1Tt8a0iqfEPcLWu+uRkr4iCNwUMKxAeOgJ0t5j8nWXi4haZJv1PEC2L6xfwdO3crYlRse417M+gpOdRlJR97bGx0G6RkaePFL6GSiqRgyLh9F6xom6D5l36E7CAX1wZgy2t0jw/xHB4F+xf7h7H2rF0PkCGCEjjEhNeNH+txAdoKqIUgpa0CncQeGJw4rteP81HgfTmN1cnS8vbO4wpjoL0mCAufjchNnulg/NVKfViYz9BDTd0fZZfMwW3h5ecItRLm0PsIB0u3dhATa59038wgz7aor3bJTu+y0tnr2F5Hnz0jJIfVbFhcWhexcFZbY6/hkjqBmzyPmnmpkePzWIKquiuc0eYlKvn3D+bVb3fso2JcuTBwjPPymQk4FibjdXJzj7ya04JvjInfJQnapYdt1WdVoTvD8I+f759QBkTSimSWOEv
