apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: araneae-reasoner
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
    path: distribution/araneae-reasoner
  destination:
    namespace: araneae-reasoner
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
