apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:

    # https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller
    # https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller

    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.5.2 # Chart version 1.5.2, Application Version 2.5.1
    chart: aws-load-balancer-controller
    helm:
      parameters:
        - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
          value: arn:aws:iam::654383687924:role/eksctl-araneae-addon-iamserviceaccount-kube-Role1-16QBSE69GWXNS
        - name: clusterName
          value: araneae
        - name: vpcId
          value: vpc-09ee3e2a7df2e29c7
        - name: region
          value: us-west-2
        - name: serviceAccount.create
          value: "true"
        - name: rbac.create
          value: "true"
        - name: resources.limits.cpu
          value: 100m
        - name: resources.limits.memory
          value: 300Mi
        - name: resources.requests.cpu
          value: 100m
        - name: resources.requests.memory
          value: 300Mi
        - name: nodeSelector.node-class
          value: utility
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
