apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-remove-default-sc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paloul/araneae.cluster.deploy.git
    targetRevision: dev
    path: distribution/aws-remove-default-sc
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
