apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:

    # https://artifacthub.io/packages/helm/cert-manager/cert-manager

    repoURL: https://charts.jetstack.io
    targetRevision: 1.12.0 # Chart version 1.12.0, App Version v1.12.0
    chart: cert-manager
    helm:
      parameters:
      - name: serviceAccount.create
        value: "true"
      - name: serviceAccount.name
        value: "cert-manager"
      - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        value: <<__role_arn.cert_manager__>>
      - name: nodeSelector.node-class
        value: utility
    
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
