# Installs the Kafka Cluster from bitnami
# 
# https://kafka.apache.org/
# https://artifacthub.io/packages/helm/bitnami/kafka
# https://github.com/bitnami/charts/tree/master/bitnami/kafka
# https://github.com/bitnami/bitnami-docker-kafka
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kafka
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.4.3 # Chart version 14.4.3, Kafka version 2.8.1
    helm:
      parameters:
      - name: commonLabels
        value: {
          "app": "kafka"
        }
      - name: global.storageClass
        value: "rook-ceph-block" # This matches the Storage Class created with rook-ceph
      - name: persistence.enabled
        value: "true"
      - name: persistence.accessModes
        value: ["ReadWriteOnce"]
      - name: persistence.size
        value: "4Gi"
      - name: persistence.storageClass
        value: "rook-ceph-block" # This matches the Storage Class created with rook-ceph
      - name: numIoThreads # The number of threads doing disk I/O
        value: 8
      - name: numNetworkThreads # The number of threads handling network requests
        value: 3
      - name: numPartitions # The default number of log partitions per topic
        value: 1
      - name: replicaCount # Number of Kafka nodes
        value: 3
      - name: nodeSelector.node-class
          value: stream
      - name: tolerations[0].only-stream
        value: "true:NoSchedule"
      - name: affinity
        value: {
          # Pod Anti Affinity will try to avoid putting pods that have labels defined here
          # This definition will try and avoid co-locating pods on the same node
          # The value needs to match the app:kafka defined in the common labels env var above
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - kafka
              topologyKey: "kubernetes.io/hostname"
        }
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
