apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  source:

    # https://github.com/kedacore/keda
    # https://artifacthub.io/packages/helm/kedacore/keda

    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.10.2 # Chart version 2.10.2, App Version 2.10.1
    chart: kedacore
    helm:
      parameters:
        - name: nodeSelector.node-class
          value: utility
        - name: crds.install # Defines whether the KEDA CRDs have to be installed or not.
          value: "true"
        
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
