apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-kserve
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paloul/araneae.cluster.deploy.git
    targetRevision: dev
    path: distribution/kubeflow/kserve
  destination:
    namespace: kubeflow
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true