apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:

    # https://artifacthub.io/packages/helm/metrics-server/metrics-server
    # https://github.com/kubernetes-sigs/metrics-server

    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.10.0 # Chart version 3.10.0, Application Version 0.6.3
    chart: metrics-server
    helm:
      parameters:
        - name: serviceAccount.create
          value: "true"
        - name: rbac.create
          value: "true"
        - name: nodeSelector.node-class
          value: core
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
