apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paloul/araneae.cluster.deploy.git
    targetRevision: dev
    path: distribution/rook-ceph
  destination:
    namespace: rook-ceph # Defined in common.yaml under rook-ceph target directory
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=false
