## ML Flow Deployment
# Some Resources based on:
# https://artifacthub.io/packages/helm/community-charts/mlflow
# https://hub.docker.com/r/burakince/mlflow
# https://artifacthub.io/packages/container/mlflow/mlflow
# https://github.com/burakince/mlflow
# The documentation on this page refers to the use of the artifact service proxy, 
# where a client does not need to know about the S3/objectstore endpoints
# https://mlflow.org/docs/latest/tracking.html#scenario-5-mlflow-tracking-server-enabled-with-proxied-artifact-storage-access

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  labels:
    app: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - name: mlflow
        securityContext: {}
        image: burakince/mlflow:2.1.1
        imagePullPolicy: Always
        command: ["mlflow"]
        args:
        - server
        - --serve-artifacts
        - --host=0.0.0.0
        - --port=5000
        - --backend-store-uri="mysql://$(MYSQL_USERNAME):$(MYSQL_PWD)@$(MYSQL_HOST):3306/$(DB_NAME)"
        - --artifacts-destination=http://minio-service.mlflow:9000
        envFrom:
        - secretRef:
            name: mlflow-mysql-secret
        - secretRef:
            name: mlflow-minio-secret
        - configMapRef:
            name: mlflow-config
        ports:
        - name: http
          containerPort: 5000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources: {}
