apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlflow

resources:
- namespace.yaml
- mlflow-deployment.yaml
- service.yaml
- mysql/mysql-sealedsecret.yaml
- mysql/mysql-pv-claim.yaml
- mysql/mysql-serviceaccount.yaml
- mysql/mysql-deployment.yaml
- mysql/istio-authorization-policy.yaml
- mysql/database-creation-job.yaml
- minio/minio-sealedsecret.yaml
- minio/minio-pv-claim.yaml
- minio/minio-service.yaml
- minio/minio-deployment.yaml
- minio/istio-authorization-policy.yaml