apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- mysql/mysql-sealedsecret.yaml
- mysql/mysql-pv-claim.yaml
- mysql/mysql-serviceaccount.yaml
- mysql/mysql-deployment.yaml
- mysql/istio-authorization-policy.yaml
- mysql/database-creation-job.yaml