kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: mysql-secret
  namespace: kubeflow
  creationTimestamp:
spec:
  template:
    metadata:
      name: mysql-secret
      namespace: kubeflow
      creationTimestamp:
    data:
  encryptedData:
    username: root
    password: SOMETHING