apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# https://github.com/kubeflow/manifests#kubeflow-pipelines
# The actual kustomization.yaml file from kubeflow v1.7.0 pipelines: 
# github.com/kubeflow/manifests/blob/v1.7.0/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user/kustomization.yaml
- github.com/kubeflow/manifests/apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user?ref=v1.7.0

patchesStrategicMerge:
- patches/minio/removals/mlpipeline-minio-artifact-secret.yaml
- patches/minio/minio-pvc.yaml
- patches/minio/minio-deployment.yaml
- patches/minio/mlpipeline-minio-secret.yaml
- patches/mysql/mlpipeline-mysql-secret.yaml
- patches/mysql/mysql-pv-claim.yaml
- patches/mysql/mysql-deployment.yaml