apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: araneae-reasoner-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: araneae-reasoner-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  commonName: reasoner.dev.araneae.io
  dnsNames:
    - reasoner.dev.araneae.io
