# Allow all traffic to the istio-ingressgateway
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  action: CUSTOM
  selector:
    # Same as the istio-ingressgateway Service selector, 
    # look in istio/istio-spec.yaml which defines and configures the Load Balancer instance
    matchLabels:
      app: istio-ingressgateway
      istio: ingressgateway
  provider:
    name: oauth2-proxy
  rules:
  - to:
    - operation:
        hosts: # These are all the hosts that Load Balancer serves
        - <<__subdomain_kubeflow_dashboard__>>.<<__domain__>>
        - <<__subdomain_kubeflow_serving__>>.<<__domain__>>
        - '*.<<__subdomain_kubeflow_serving__>>.<<__domain__>>'
