apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# https://github.com/kubeflow/manifests#tensorboard
# The actual kustomization.yaml file from kubeflow v1.7.0 Tensorboard Controller
# github.com/kubeflow/manifests/blob/v1.7.0/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow/kustomization.yaml
- github.com/kubeflow/manifests/apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow?ref=v1.7.0
