kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: mlflow-minio-secret
  namespace: mlflow
  creationTimestamp: null
spec:
  template:
    metadata:
      name: mlflow-minio-secret
      namespace: mlflow
      creationTimestamp: null
  encryptedData:
    AWS_ACCESS_KEY_ID: AgB+U5oeKKLqCyv1PsPc4jFLNVuud7/UnOP/sJGlBFjUzSDKNI8q35J+QcCB0vGMwWCd9TgI9htSeXBSCzxhFG+T/2XvUocCiS3lw6a4VEtWzvZhB0Pmo6MYe5Ems5a9DNdcNfUcXebpVp8KpkgSjab9cWL3p95vNjzN1A+My6imvP7dkNGKsHIlDBxBkZrXAdLQ13cL9/28A3c8zDOVceD5H6SjqGLs8BxP/Npt9FW6n29bUjlJpZBADM2U4LUJUbU9oqyJnBzLS51kMOsthF6xi7SiF1Pbs60CcT2pfa0t9ABnd4TdES/FDnSs2OOhdy1AazpVVtEwXq9yPiA6NULjE/0KIevV7HihoszLjlt+gU8yY/D01824D5Gyj0vbcgQLMpJOh6ion2vKU1J2QsQDPqvqpWRfJjG2zr9hm01qnlUhd1rXRHjzY9tnfGNsTZ9Kt82GfeLF4NT4vFZOR/+74dQ4Nwq9mhDI8FfBnsSEzeeXHsje3FkESuhPZl9J3t8lipmlffvER3j42yKeFfmfnK5LQJpvYLCRlrIrh5reB02GbN6HWE5tVW5KroRs4sSE2aHOpg8mvCioiU5MGtHojqRCu9HCMffkpZkyvaBOvMFccq/MHmt0WYKIdnizIJbMVS1DhugU5+dUIq14LsOfwQTVf2wJfcIcMOvwgT0dmS/CUJLj257mpQ6AQeUSG19lJll15I+TZj3qnynibegEPjb7fqPxyuT5GYZEU9ZyxA==
    AWS_SECRET_ACCESS_KEY: AgBEfGcquooitMq3bAIZC/6wYAIKz2MpGSS/mtncCRrEavm4Ijk1NY5go3qsz/folm+luLZu0RNyT8Ejtp9EY1plc4OTmcUNPFcHPlCEtuM/6Ob5Q72/Mcm2iuBFUD7+JttLy4ixtXZ2gEBSy4Sca+eAE8nWRdwZKOvdfub8iyOMfu+2U90sdy+jWGHrGKvilFtVd7emZIlmk/rtm+3Ndex1UTHLQz7d5wX3L8epr4yxHXjvS9Gib7SgwiQhCkKEa8dIA4b5R2PS4TKSeQS/4NHj+isaJqivXVygKgpT8LHlu/oM0xwy+qImtDDmvvIPp6S0vslFYNMJbrUuE86WNHSpkI9+G0oqkfTAihXVHwkalFr/o6IF4oTErRDYTesX08kIDuXflGyvk+7nt56NbKdkINSxJdpe7jJ8iIH/ZUgNOgsXusj9V6D8QDlVE/Fin3O3ZzR28kbw6qM9fVQUgTAh/FT4562Wpj6XdTTIFGbNctimxZUcgtXSNmDuTLr14bGnfoe9HyBehMLQTjXE8SMR3u53YPIRJEBC3NJOIcaTmN/AQZHVUYjbUX2LUVpCy0U+hc1CKMPiYo+pGuhqFqVSnRhPGREdECZZdy8fG56EYe4IH+4Rq7WVyA5YEphw4E/3qy8WUHkaN5/mg+IpyNxaLuN2hh4gli4FOl9zQ9ubUiiIhb8w3AUm42/e6UA9XAz+uglMbXmn9SrVdHFDLV/j/jq7RUzwkUeG6TyecxB1Yw==
