apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-minio-pv-claim
  namespace: mlflow
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
