kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-secret
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-secret
      namespace: auth
      creationTimestamp: null
  encryptedData:
    admin-password: AgBtHofG55z0Jfh6FiP/ryQOWFLTxknLd+cEEIPclluLwMZFzQM5xMBYTJz9n3wIuXGGumD36pTSTjB+2bx+tdByytqHV3u5CNJh9raeYQPYiWff4lMxfSGnY2Ay+8z+hOhTUjI3vlMIHLgbE4LamoZpy450FI3bGAjQBLzfOUNFfAxlztjnz2M3M1hQpGCkllk03vfF8rSwO057JkxG22m6XgzCjrHnvFe863CdBPssY1PNSANZKSt+En4vebkLo4z5Othh7cDaAYBQ0eJ2RcvVP3+26O+97zRpiQSwUn8KouSuPWr+3TNz0QEFF/2UEuktuTWFY/fJVt5c+nCZM8hHBgXAI38I2jeshRRVarL3EtMFcrMVAcCdhsUD9IDH7CnT5zUQ9fKlTtC9pXl7YzL0o4bMvAQqBmIo17z4nKT3j158m/VSgPeLJPRCn5KlFu/V22dR9CPfbcLHaQXlH3CAP5oeqa01/P/3p6tGJgcLev/3j3S666D6Cjjtus/K1kjYEpYueJswpA71G79x61XTXZ/ekyFxQKHNQ0IVTxMxVs04PXKcb1iLiwd4uCacH7kM/wJjxkkZHosefdqxPx4XC1KrQjGnBWTdLZ8VO/HrFz/wMk3S8AZ4ju4mhjwm0opbSadwdi7hPLzpH7lKaYpbpQqKJj0TB0h/SSwbQvedEtoB3F/qZ34i1JuaLoS9ViQDKPdlpSmqxwfGb8XFvrvYdkkRdUaA3VscIj+RMoa+tg==
