kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: keycloak-secret
  namespace: auth
  creationTimestamp: null
spec:
  template:
    metadata:
      name: keycloak-secret
      namespace: auth
      creationTimestamp: null
  encryptedData:
    admin-password: AgA7iAaTNzY5UORj6W+Ba4YiU1tY9/Kay5Y0XLlSfVx6nrQg32kb2fAWv5C9pHyXMdb3fkVTfcWEYNB9p3JDTvoqahyTZWaPrd5y5RFXP3rzehgb3LJ3BKGxKomeLp9tbBKXCO4cfjwOZ3g6iMXyyV+0mi1y+NOVQW2X2L9Xknxb6+lHaxIGtnqfmVASxIUdVWHDLfMFDxH/WYgH5VI99YA9cSMP/Uhit6XpzGuQLaV0V2WTea/KR44pRkbtmmvmrfLGXN69VF2VNj/bDNiX7ZmGrwUlfPLJvfElzHkgUpPJa9pc7U8dK2mV93vPDoXiuTSoz51dvI7vTZ43rXpeuK9ZrnN45lzF3t35WnQmLsmKLhAtle3U+Km7JTOxOk4MoiMg2k85KxC06+ixJX1SKGxTCmk7Z7bQxt9JEOR3bsLIPK1k8Lc0cKSjlJXsc79OlQb5lbPEoJV8IDRY/fv+NFNp3j81DPcCOqOSbHEOIS55Q4OAJKsOXjrD1NGSUOiGCq2mVA9ASClSXpWpVP+2K2jZynPJW4ESQJYPKOtgf0QB4yCL2emprtrTahkoH4ZM9QufHEoUD76zhRwp24DCZAj5Cf6yQQsBgmuvFwRmYGrZXlljsITEXUkq5PoNqoKGSyXDE9PL3BhudcQhU+C+rUeOwyhvl1E9Ih/vp7YajeuEZC+dpO+YVS6I7yo6yDwB2/OYszJATHzckXDODC/T9EPGTDSkRw9ILgyAGtYT+PrZJA==
