apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- keycloak-secret.yaml
- keycloak-postgresql-secret.yaml
- araneae-realm-secret.yaml
- oauth2-proxy-secret.yaml
- virtual-service.yaml
- keycloak.yaml

patchesStrategicMerge:
- oauth2-proxy-signout-virtual-service.yaml
- oauth2-proxy-patch.yaml
- removals/oauth2-proxy-secret.yaml