apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: oauth2-proxy-logout
  namespace: auth
spec:
  gateways:
  - araneae/araneae-gateway
  hosts:
  - <<__subdomain_dashboard__>>.dev.araneae.io
  http:
  - match:
    - uri:
        prefix: /logout
    rewrite:
      uri: /oauth2/sign_out
    route:
    - destination:
        host: oauth2-proxy.auth.svc.cluster.local
        port:
          number: 4180
    headers:
      request:
        set:
          X-Auth-Request-Redirect: https://auth.dev.araneae.io/auth/realms/araneae/protocol/openid-connect/logout?redirect_uri=https%%3A%%2F%%2F<<__subdomain_dashboard__>>.dev.araneae.io